type key={
    text: string,
    value: string,
}
export const Keys: key[]= [
    {   text: '',
        value: '',
    },
    {   text: 'forward',
        value: 'f',
    },
    {   text: '',
        value: '',
    },
    {   text: 'left',
        value: 'l',
    },
    {   text: '',
        value: '',
    },
    {   text: 'right',
        value: 'r',
    },
    {   text: '',
        value: '',
    },
    {   text: 'backward',
        value: 'b',
    },
    {   text: '',
        value: '',
    },
];